module: datamodules.waterbodies.WBDM
# dims per var per file
batch_size: 12
mask_ratio: 0.5
dirs:
  ims: ${dataset.dirs.main}Images/
  masks: ${dataset.dirs.main}Masks/
dims:
  height: 512
  width: 512
test_size: 0.2
val_size: 0.2
seed: 14
normalize: True
