_target_: datamodules.waterbodies.WBDM
batch_size: 12
mask_ratio: 0.5
test_size: 0.2
val_size: 0.2
seed: 14
normalize: True

# dataset class
Dataset:
  _target_: datamodules.waterbodies.WBDS
  dir_ims: ${datamodule.dir}Images/
  dir_masks: ${datamodule.dir}Masks/
  height: 512
  width: 512
