_target_: models.base.BinaryClass

net:
  _target_: segmentation_models_pytorch.Unet
  # encoder_name: resnet50
  encoder_name: mobilenet_v2
  encoder_weights: imagenet
  in_channels: 3
  classes: 1
  activation: sigmoid

criterion:
  _target_: segmentation_models_pytorch.losses.DiceLoss
  mode: binary

accuracy:
  _target_: torchmetrics.classification.Accuracy
  task: binary

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
