_target_: models.vitmae.ViTMAEmodule
wandb_plots: False
# num_labels: 10

net:
  _target_: transformers.ViTForImageClassification.from_pretrained
  pretrained_model_name_or_path: "google/vit-base-patch16-224"
  num_labels: 10
  ignore_mismatched_sizes: True

criterion:
  _target_: torch.nn.CrossEntropyLoss

accuracy:
  _target_: torchmetrics.classification.Accuracy
  task: multiclass
  num_classes: 10

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
  # weight_decay: 0.9
