_target_: lightning.pytorch.trainer.Trainer

callbacks:
  # - _target_: lightning.pytorch.callbacks.BatchSizeFinder
  # - _target_: lightning.pytorch.callbacks.Timer
  #   duration: 00:00:01:00
  # - _target_: lightning.pytorch.callbacks.LearningRateMonitor
  # - _target_: lightning.pytorch.callbacks.LearningRateFinder
  - _target_: lightning.pytorch.callbacks.RichModelSummary
  - _target_: lightning.pytorch.callbacks.RichProgressBar
  - _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: train_loss

default_root_dir: ${output_dir}

min_epochs: 1 # prevents early stopping
# max_epochs: 50

accelerator: auto
devices: auto
strategy: auto

# mixed precision for extra speed-up
precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
