defaults:
  - model: unet
  - dataset: waterbodies
  - wandb_init: defaults
  - _self_ # as last argument to allow the override of parameters via this main config
#    Decomment this parameter to get parallel job running

stage: train
save_model: True
plot_results: True
output_dir: ${hydra:runtime.cwd}/outputs/
save_model_path: ${output_dir}saved_models/${dataset_name}_${model_name}_temp.pkl
load_model_path: ${output_dir}saved_models/${dataset_name}_${model_name}_temp.pkl
output_dir_plots: ${output_dir}plots/${group_name}/
# for wandb logging
log_to_wandb: False
project_name: ml_template
model_name: ${hydra:runtime.choices.model}
dataset_name: ${hydra:runtime.choices.dataset}
group_name: ${dataset_name}_${model_name}

dataset:
  dirs:
    parent: ${hydra:runtime.cwd}/datasets/
    main: ${dataset.dirs.parent}${dataset_name}/
  normalize: True
  test_size: 0.2
  val_size: 0.2
  seed: 142

# do not change below
datamodule_inst:
  _target_: ${dataset.module}
  cfg: ${dataset}
model_inst:
  _target_: ${model.module}
  cfg: ${model}
